"""
Shared catalog data for ShopinglyX.

This module is the single source of truth for the demo catalog:
- generate_placeholder_images.py reads it to render product/category images
- store/management/commands/seed_products.py reads it to populate the database

Keeping the data in one place means the images and the database rows always
line up (same names, same order, same categories).
"""

CATEGORIES = [
    {
        "name": "Electronics",
        "slug": "electronics",
        "color": "#2563eb",
        "color_end": "#1e3a8a",
        "icon": "chip",
        "products": [
            ("Wireless Bluetooth Earbuds Pro", 2999, 2299, 4.5, True,
             "True wireless earbuds with active noise cancellation and 30-hour battery life."),
            ("4K Ultra HD Smart TV 55\"", 45999, 38999, 4.6, True,
             "Cinematic 4K HDR display with built-in streaming apps and voice remote."),
            ("Noise Cancelling Over-Ear Headphones", 6999, None, 4.4, False,
             "Studio-quality sound with adaptive noise cancellation for long listening sessions."),
            ("Fast Charging Power Bank 20000mAh", 1499, 1199, 4.3, False,
             "High-capacity power bank with dual USB-C fast charging ports."),
            ("Mechanical Gaming Keyboard RGB", 3499, 2799, 4.5, True,
             "Hot-swappable mechanical switches with per-key RGB lighting."),
            ("Wireless Mouse Ergonomic", 999, None, 4.2, False,
             "Silent-click ergonomic mouse designed for all-day comfort."),
            ("Smartwatch Fitness Tracker", 4999, 3999, 4.4, True,
             "Track heart rate, sleep, and workouts with a week-long battery life."),
            ("Portable Bluetooth Speaker", 1999, 1599, 4.3, False,
             "Compact waterproof speaker with rich bass and 12-hour playtime."),
            ("USB-C Hub 7-in-1", 1799, None, 4.1, False,
             "Expand a single USB-C port into HDMI, USB-A, SD card, and more."),
            ("Laptop Stand Adjustable Aluminum", 1299, None, 4.5, False,
             "Ergonomic aluminum stand that improves posture and laptop airflow."),
        ],
    },
    {
        "name": "Fashion",
        "slug": "fashion",
        "color": "#db2777",
        "color_end": "#831843",
        "icon": "shirt",
        "products": [
            ("Men's Slim Fit Denim Jacket", 2499, 1999, 4.3, True,
             "Classic denim jacket with a modern slim fit and durable stitching."),
            ("Women's Floral Summer Dress", 1799, None, 4.4, True,
             "Lightweight breathable fabric with a flattering floral print."),
            ("Classic Leather Wallet", 999, 799, 4.5, False,
             "Genuine leather bifold wallet with RFID-blocking card slots."),
            ("Unisex Canvas Sneakers", 1599, None, 4.2, False,
             "Everyday sneakers with a cushioned sole and breathable canvas upper."),
            ("Wool Blend Overcoat", 4999, 3999, 4.6, True,
             "Tailored overcoat in a warm wool blend, perfect for winter layering."),
            ("Cotton Graphic T-Shirt", 599, None, 4.1, False,
             "Soft 100% cotton tee with a modern graphic print."),
            ("Women's High-Waist Jeans", 2199, 1799, 4.3, False,
             "Stretch denim jeans with a flattering high-waist fit."),
            ("Men's Formal Dress Shirt", 1499, None, 4.2, False,
             "Wrinkle-resistant formal shirt suited for office and events."),
            ("Leather Ankle Boots", 3299, 2699, 4.4, False,
             "Handcrafted leather boots with a comfortable rubber sole."),
            ("Polarized Aviator Sunglasses", 1299, 999, 4.3, False,
             "UV-protective polarized lenses in a timeless aviator frame."),
        ],
    },
    {
        "name": "Home & Kitchen",
        "slug": "home-kitchen",
        "color": "#16a34a",
        "color_end": "#14532d",
        "icon": "home",
        "products": [
            ("Non-Stick Cookware Set 10-Piece", 4499, 3599, 4.5, True,
             "Durable non-stick cookware set covering all your everyday cooking needs."),
            ("Stainless Steel Electric Kettle", 1499, None, 4.4, False,
             "Fast-boiling 1.7L kettle with auto shut-off and boil-dry protection."),
            ("Robot Vacuum Cleaner", 12999, 9999, 4.3, True,
             "Smart mapping robot vacuum with app control and auto-recharge."),
            ("Memory Foam Pillow Set", 1799, 1399, 4.5, False,
             "Contoured memory foam pillows for neck and spine support."),
            ("Air Fryer Digital 5.5L", 5499, 4499, 4.6, True,
             "Oil-free frying with digital presets for crispy, healthier meals."),
            ("Ceramic Dinnerware Set 16-Piece", 3299, None, 4.3, False,
             "Elegant ceramic dinnerware set for four, dishwasher and microwave safe."),
            ("Blackout Curtains Pair", 1699, 1299, 4.2, False,
             "Thermal-insulated curtains that block light and reduce noise."),
            ("Stand Mixer 6-Speed", 8999, 7499, 4.6, False,
             "Powerful stand mixer with multiple attachments for baking."),
            ("Bamboo Cutting Board Set", 999, None, 4.4, False,
             "Eco-friendly bamboo boards in three sizes with juice grooves."),
            ("Smart LED Desk Lamp", 1899, 1499, 4.3, False,
             "Touch-control desk lamp with adjustable brightness and color temperature."),
        ],
    },
    {
        "name": "Beauty & Personal Care",
        "slug": "beauty-personal-care",
        "color": "#f59e0b",
        "color_end": "#92400e",
        "icon": "sparkle",
        "products": [
            ("Vitamin C Brightening Serum", 899, 699, 4.5, True,
             "Antioxidant-rich serum that brightens skin and evens out tone."),
            ("Hydrating Face Moisturizer", 749, None, 4.4, False,
             "Lightweight, non-greasy moisturizer for 24-hour hydration."),
            ("Professional Hair Dryer", 2999, 2399, 4.3, True,
             "Ionic hair dryer with multiple heat settings for salon-quality results."),
            ("Electric Facial Cleansing Brush", 1499, 1199, 4.2, False,
             "Silicone cleansing brush that gently exfoliates and deep-cleans pores."),
            ("Matte Liquid Lipstick Set", 1199, None, 4.4, False,
             "Long-wearing matte lipstick set in six versatile shades."),
            ("Argan Oil Hair Mask", 649, 499, 4.5, False,
             "Deep-conditioning hair mask enriched with pure argan oil."),
            ("Rechargeable Electric Shaver", 2499, 1999, 4.3, False,
             "Cordless shaver with a precision blade system for a smooth shave."),
            ("SPF 50 Sunscreen Lotion", 549, None, 4.6, True,
             "Broad-spectrum SPF 50 protection in a lightweight, non-sticky formula."),
            ("Ceramic Hair Straightener", 1899, 1499, 4.2, False,
             "Fast-heating ceramic plates for smooth, frizz-free styling."),
            ("Organic Bath Bomb Gift Set", 999, None, 4.4, False,
             "A set of six handmade, essential-oil infused bath bombs."),
        ],
    },
    {
        "name": "Sports & Fitness",
        "slug": "sports-fitness",
        "color": "#dc2626",
        "color_end": "#7f1d1d",
        "icon": "dumbbell",
        "products": [
            ("Adjustable Dumbbell Set", 5999, 4999, 4.5, True,
             "Space-saving dumbbells that adjust from 5 to 25 lbs per side."),
            ("Yoga Mat Non-Slip Extra Thick", 999, None, 4.4, False,
             "Extra-cushioned yoga mat with a non-slip textured surface."),
            ("Running Shoes Lightweight", 2999, 2399, 4.3, True,
             "Breathable mesh running shoes with responsive cushioning."),
            ("Resistance Bands Set", 799, 599, 4.2, False,
             "Five-band resistance set for strength training and rehab."),
            ("Foldable Treadmill Compact", 24999, 19999, 4.4, True,
             "Space-saving foldable treadmill with speed and incline control."),
            ("Insulated Sports Water Bottle", 699, None, 4.5, False,
             "Double-wall insulated bottle that keeps drinks cold for 24 hours."),
            ("Cycling Helmet Aerodynamic", 1799, 1399, 4.3, False,
             "Lightweight aerodynamic helmet with adjustable ventilation."),
            ("Camping Tent 4-Person", 5499, 4499, 4.4, False,
             "Weatherproof 4-person tent that sets up in minutes."),
            ("Adjustable Jump Rope", 499, None, 4.1, False,
             "Speed jump rope with a smooth ball-bearing rotation."),
            ("Foam Roller Muscle Recovery", 899, 699, 4.3, False,
             "High-density foam roller for post-workout muscle recovery."),
        ],
    },
    {
        "name": "Books & Stationery",
        "slug": "books-stationery",
        "color": "#7c3aed",
        "color_end": "#4c1d95",
        "icon": "book",
        "products": [
            ("The Art of Modern Cooking (Hardcover)", 1499, 1199, 4.6, True,
             "A beautifully illustrated hardcover guide to modern home cooking."),
            ("Bestselling Mystery Novel Collection", 1999, None, 4.5, False,
             "A boxed set of five gripping bestselling mystery novels."),
            ("Leather Bound Journal", 799, 599, 4.4, False,
             "A handcrafted leather journal with 200 pages of premium paper."),
            ("Premium Gel Pen Set", 499, None, 4.3, False,
             "A 20-color gel pen set ideal for journaling and art."),
            ("Kids' Illustrated Storybook Bundle", 1299, 999, 4.5, True,
             "A colorful bundle of ten illustrated storybooks for young readers."),
            ("Productivity Planner 2026", 899, None, 4.4, False,
             "A daily planner designed to help you set and track goals."),
            ("Watercolor Sketchbook", 649, 499, 4.2, False,
             "Heavyweight paper sketchbook built for watercolor and mixed media."),
            ("Classic Literature Boxset", 2499, 1999, 4.6, False,
             "A collector's boxset of ten timeless literary classics."),
            ("Fountain Pen Calligraphy Set", 1199, None, 4.3, False,
             "A beginner-friendly calligraphy set with three nib sizes."),
            ("Desk Organizer with Notepad", 699, 549, 4.1, False,
             "A wooden desk organizer with a built-in notepad holder."),
        ],
    },
    {
        "name": "Toys & Games",
        "slug": "toys-games",
        "color": "#0891b2",
        "color_end": "#164e63",
        "icon": "puzzle",
        "products": [
            ("Building Blocks Creative Set 500pc", 1999, 1599, 4.6, True,
             "A 500-piece building block set that sparks creative construction."),
            ("Remote Control Racing Car", 2499, 1999, 4.4, True,
             "High-speed RC car with responsive steering and rechargeable battery."),
            ("Educational STEM Robot Kit", 3499, 2799, 4.5, True,
             "A buildable robot kit that teaches coding and engineering basics."),
            ("Plush Teddy Bear Large", 999, None, 4.3, False,
             "An extra-soft, huggable teddy bear that makes a perfect gift."),
            ("Strategy Board Game Family Edition", 1599, None, 4.5, False,
             "A family-friendly strategy game for 2 to 6 players."),
            ("Puzzle 1000-Piece Landscape", 799, 599, 4.2, False,
             "A beautifully detailed 1000-piece landscape jigsaw puzzle."),
            ("Action Figure Collector Set", 1799, 1399, 4.3, False,
             "A set of five poseable, highly detailed collector action figures."),
            ("Kids' Art & Craft Kit", 1299, 999, 4.4, False,
             "An all-in-one craft kit with paints, brushes, and paper crafts."),
            ("Wooden Train Set", 1899, None, 4.5, False,
             "A classic wooden train set with expandable track pieces."),
            ("Drone with HD Camera for Kids", 3999, 3199, 4.3, False,
             "A beginner-friendly drone with altitude hold and an HD camera."),
        ],
    },
    {
        "name": "Grocery & Gourmet",
        "slug": "grocery-gourmet",
        "color": "#65a30d",
        "color_end": "#365314",
        "icon": "leaf",
        "products": [
            ("Organic Extra Virgin Olive Oil 1L", 899, None, 4.6, True,
             "Cold-pressed extra virgin olive oil sourced from organic groves."),
            ("Premium Roasted Coffee Beans 1kg", 1199, 999, 4.7, True,
             "Freshly roasted, single-origin coffee beans with a rich aroma."),
            ("Assorted Dry Fruits Gift Box", 1499, 1199, 4.5, False,
             "A premium assortment of almonds, cashews, and dried fruits."),
            ("Herbal Green Tea Pack (100 bags)", 599, None, 4.3, False,
             "A soothing herbal green tea blend, 100 individually sealed bags."),
            ("Artisan Dark Chocolate Collection", 999, 799, 4.6, False,
             "A curated collection of single-origin dark chocolate bars."),
            ("Organic Honey Raw & Unfiltered", 649, None, 4.5, False,
             "Raw, unfiltered honey harvested from organic wildflower farms."),
            ("Whole Wheat Pasta Pack", 349, None, 4.2, False,
             "Nutritious whole wheat pasta made from 100% durum wheat."),
            ("Spice Rack Gourmet Set", 1399, 1099, 4.4, False,
             "A 12-jar gourmet spice set covering global flavor profiles."),
            ("Cold-Pressed Almond Oil", 799, 649, 4.3, False,
             "Pure cold-pressed almond oil for cooking and skincare."),
            ("Multigrain Breakfast Cereal", 449, None, 4.1, False,
             "A wholesome multigrain cereal packed with fiber and nutrients."),
        ],
    },
    {
        "name": "Furniture",
        "slug": "furniture",
        "color": "#92400e",
        "color_end": "#451a03",
        "icon": "sofa",
        "products": [
            ("Ergonomic Office Chair Mesh Back", 8999, 6999, 4.5, True,
             "A breathable mesh-back office chair with lumbar support."),
            ("Modern L-Shaped Sofa", 34999, 27999, 4.6, True,
             "A spacious L-shaped sofa upholstered in durable fabric."),
            ("Solid Wood Dining Table Set", 24999, 19999, 4.5, False,
             "A six-seater solid wood dining table with matching chairs."),
            ("Bookshelf 5-Tier Industrial", 5499, 4499, 4.3, False,
             "An industrial-style 5-tier bookshelf with a metal frame."),
            ("Queen Size Platform Bed Frame", 14999, 11999, 4.4, True,
             "A sturdy platform bed frame with a minimalist wooden headboard."),
            ("Folding Study Desk Compact", 3499, 2799, 4.2, False,
             "A space-saving folding desk perfect for small rooms."),
            ("TV Entertainment Unit", 9999, 7999, 4.3, False,
             "A modern entertainment unit with cable management and storage."),
            ("Bedside Nightstand with Drawer", 2999, None, 4.4, False,
             "A compact nightstand with a soft-close drawer and open shelf."),
            ("Recliner Armchair Plush", 12999, 9999, 4.5, False,
             "A plush recliner armchair with a smooth reclining mechanism."),
            ("Shoe Storage Cabinet", 4499, 3599, 4.2, False,
             "A slim shoe cabinet that stores up to 24 pairs of shoes."),
        ],
    },
    {
        "name": "Automotive",
        "slug": "automotive",
        "color": "#1e293b",
        "color_end": "#0f172a",
        "icon": "car",
        "products": [
            ("Car Dash Camera Full HD", 2999, 2399, 4.4, True,
             "1080p dash camera with loop recording and night vision."),
            ("Portable Tire Inflator", 1999, 1599, 4.3, False,
             "A compact 12V tire inflator with a digital pressure gauge."),
            ("Universal Car Phone Mount", 599, None, 4.2, False,
             "A one-handed phone mount that fits any vent or dashboard."),
            ("Microfiber Car Cleaning Cloths", 499, None, 4.5, False,
             "A pack of 12 lint-free microfiber cloths for a streak-free shine."),
            ("LED Headlight Bulb Kit", 2499, 1999, 4.3, False,
             "Bright, energy-efficient LED headlight bulbs, easy plug-and-play install."),
            ("Car Seat Covers Set", 3499, 2799, 4.2, True,
             "A full set of durable, water-resistant car seat covers."),
            ("Bluetooth OBD2 Scanner", 1799, 1399, 4.4, False,
             "A wireless OBD2 scanner that reads engine codes via your phone."),
            ("Car Vacuum Cleaner Portable", 1599, 1299, 4.3, False,
             "A compact 12V vacuum built for quick interior cleanups."),
            ("All-Weather Floor Mats", 2199, None, 4.4, False,
             "Heavy-duty all-weather floor mats that trap dirt and moisture."),
            ("Jump Starter Power Pack", 4999, 3999, 4.5, False,
             "A portable jump starter with USB charging and an LED flashlight."),
        ],
    },
]
